// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsy_RS1mzmxoHkRX6iMviPS2yv29pufQA',
    appId: '1:518203824425:web:308814b63db2d6049dff38',
    messagingSenderId: '518203824425',
    projectId: 'doona-4ac15',
    authDomain: 'doona-4ac15.firebaseapp.com',
    storageBucket: 'doona-4ac15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB212wPj_gHz0ZRKjWG-_LLo989qti2aVE',
    appId: '1:518203824425:android:63e767a35472280a9dff38',
    messagingSenderId: '518203824425',
    projectId: 'doona-4ac15',
    storageBucket: 'doona-4ac15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItGjm-NTQgCrQcaQhiMJH3QqlEU9e89M',
    appId: '1:518203824425:ios:bf8eee184b3583f19dff38',
    messagingSenderId: '518203824425',
    projectId: 'doona-4ac15',
    storageBucket: 'doona-4ac15.firebasestorage.app',
    iosBundleId: 'com.example.doona',
  );
}
